spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/dbvotos
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest   
  boot:
    admin:
      client:
        url: http://127.0.0.1:8081        

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      